version: "3.6"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - front_tier
    restart: always
  dnsmasq:
    image: andyshinn/dnsmasq:2.83
    container_name: dnsmasq
    command:
      - '--address=/api.noondaysun.org/127.0.0.1/'
      - '--server=8.8.8.8'
    ports:
      - "53:53"
      - "53:53/udp"
    networks:
      - front_tier
    cap_add:
      - NET_ADMIN
    restart: always
  nginx:
    container_name: nginx
    image: nginx:latest
    networks:
      - front_tier
    restart: on-failure
    volumes:
      - ./app:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      VIRTUAL_HOST: local.kiddsbooks.com
  php:
    container_name: php
    build:
      context: .
    expose:
      - 9000
    networks:
      - front_tier
      - back_tier
    restart: on-failure
    volumes:
      - ./app:/var/www
    working_dir: /var/www
  redis:
    container_name: redis
    image: redis:6-alpine
    networks:
      - front_tier
    restart: always
  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file:
      - .env
    networks:
      - back_tier

networks:
  back_tier:
  front_tier:
