version: "3.4"
services:
  unit:
    build:
      context: .
      dockerfile: ./Dockerfile
      cache_from:
        - nginx/unit:1.18.0-php7.3
    container_name: 'kiddsbooks'
    ports:
      - 80:80
      - 443:443
    networks:
      - front-tier
      - back-tier
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: 'kiddsbooks'
      MYSQL_USER: 'user'
    healthcheck:
      test: ["CMD", "mysqlshow"]
      interval: 2m30s
      timeout: 15s
      retries: 3
    expose:
      - 3600
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: