version: "2.3"

services:

### PHP-FPM Container #######################################

  php-fpm:
    container_name: php-fpm
    hostname: php-fpm
    image: mikechernev/php7-fpm-laravel:latest
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

### NGINX Server Container ##################################

  nginx:
    depends_on:
      - php-fpm
      - mysql
    extra_hosts:
      - kiddsbooks.com:127.0.0.1
    healthcheck:
      test:
        ["CMD", "wget", "-O", "-", "http://kiddsbooks.com/status"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    image: nginx:mainline-alpine
    links:
      - php-fpm
      - redis
    ports:
      - "80:80"
    volumes:
      - ./docker-config/nginx/conf.d/:/etc/nginx/conf.d/

### MySQL Container #########################################

  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=JVTYHR^yfrhd2w7
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=JFJWRTP%375ahjwsg
    healthcheck:
      test:
        ["CMD", "mysql", "-h", "localhost", "-u", "root", "-p", "115kke9Hua", "-e", "SHOW DATABASES"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    image: mysql:latest
    volumes:
      - ./data:/var/lib/mysql

### REDIS Container #########################################

  redis:
    image: redis:alpine
    healthcheck:
      test:
        ["CMD", "redis-cli", "-h", "127.0.0.1", "info"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
