name: CI Workflow

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Check out Git repository
        uses: actions/checkout@v2
      # Docker
      - name: DockerCompose Lint
        run: docker-compose config -q
      - name: hadolint
        uses: brpaz/hadolint-action@master
      # PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
          coverage: none
          tools: composer
      - name: Install PHP dependencies and CI
        run: |
          cd app/kiddsbooks.com && \
          cp .env.test .env && \
          composer install --prefer-dist --no-progress --no-ansi --no-interaction && \
          echo "vendor/bin" >> $GITHUB_PATH && \
          composer ci

